// automatically generated by the FlatBuffers compiler, do not modify

package AllWatchSerialize;

public final class Attributes {
  private Attributes() { }
  public static final byte NONE = 0;
  public static final byte LayoutAttributes = 1;
  public static final byte TextAttributes = 2;
  public static final byte ShapeAttributes = 3;
  public static final byte CardAttributes = 4;

  public static final String[] names = { "NONE", "LayoutAttributes", "TextAttributes", "ShapeAttributes", "CardAttributes", };

  public static String name(int e) { return names[e]; }
}

