// automatically generated by the FlatBuffers compiler, do not modify

package AllWatchSerialize;

public final class CommandType {
  private CommandType() { }
  public static final byte NONE = 0;
  public static final byte Handshake = 1;
  public static final byte Application = 2;
  public static final byte Action = 3;
  public static final byte View = 4;

  public static final String[] names = { "NONE", "Handshake", "Application", "Action", "View", };

  public static String name(int e) { return names[e]; }
}

