// automatically generated by the FlatBuffers compiler, do not modify

package AllWatchSerialize;

public final class Components {
  private Components() { }
  public static final byte NONE = 0;
  public static final byte ProgressBar = 1;
  public static final byte ImageBackground = 2;

  public static final String[] names = { "NONE", "ProgressBar", "ImageBackground", };

  public static String name(int e) { return names[e]; }
}

