// automatically generated by the FlatBuffers compiler, do not modify

package AllWatchSerialize;

public final class DefaultStyle {
  private DefaultStyle() { }
  public static final short Notification = 0;
  public static final short TextWall = 1;
  public static final short ToBottom = 2;
  public static final short ToTop = 3;
  public static final short Center = 4;

  public static final String[] names = { "Notification", "TextWall", "ToBottom", "ToTop", "Center", };

  public static String name(int e) { return names[e]; }
}

