// automatically generated by the FlatBuffers compiler, do not modify

package AllWatchSerialize;

public final class DefaultDatatypes {
  private DefaultDatatypes() { }
  public static final short Text = 0;
  public static final short Media = 1;
  public static final short List = 2;
  public static final short Map = 3;
  public static final short Custom = 4;

  public static final String[] names = { "Text", "Media", "List", "Map", "Custom", };

  public static String name(int e) { return names[e]; }
}

