// automatically generated by the FlatBuffers compiler, do not modify

package AllWatchSerialize;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class Id extends Table {
  public static Id getRootAsId(ByteBuffer _bb) { return getRootAsId(_bb, new Id()); }
  public static Id getRootAsId(ByteBuffer _bb, Id obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public Id __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String packageName() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer packageNameAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer packageNameInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public String friendlyName() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer friendlyNameAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer friendlyNameInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }

  public static int createId(FlatBufferBuilder builder,
      int packageNameOffset,
      int friendlyNameOffset) {
    builder.startObject(2);
    Id.addFriendlyName(builder, friendlyNameOffset);
    Id.addPackageName(builder, packageNameOffset);
    return Id.endId(builder);
  }

  public static void startId(FlatBufferBuilder builder) { builder.startObject(2); }
  public static void addPackageName(FlatBufferBuilder builder, int packageNameOffset) { builder.addOffset(0, packageNameOffset, 0); }
  public static void addFriendlyName(FlatBufferBuilder builder, int friendlyNameOffset) { builder.addOffset(1, friendlyNameOffset, 0); }
  public static int endId(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

