// automatically generated by the FlatBuffers compiler, do not modify

package AllWatchSerialize;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class LayoutAttributes extends Table {
  public static LayoutAttributes getRootAsLayoutAttributes(ByteBuffer _bb) { return getRootAsLayoutAttributes(_bb, new LayoutAttributes()); }
  public static LayoutAttributes getRootAsLayoutAttributes(ByteBuffer _bb, LayoutAttributes obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public LayoutAttributes __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public short spacing() { int o = __offset(4); return o != 0 ? bb.getShort(o + bb_pos) : 0; }

  public static int createLayoutAttributes(FlatBufferBuilder builder,
      short spacing) {
    builder.startObject(1);
    LayoutAttributes.addSpacing(builder, spacing);
    return LayoutAttributes.endLayoutAttributes(builder);
  }

  public static void startLayoutAttributes(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addSpacing(FlatBufferBuilder builder, short spacing) { builder.addShort(0, spacing, 0); }
  public static int endLayoutAttributes(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

