// automatically generated by the FlatBuffers compiler, do not modify

package AllWatchSerialize;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class ProgressBar extends Table {
  public static ProgressBar getRootAsProgressBar(ByteBuffer _bb) { return getRootAsProgressBar(_bb, new ProgressBar()); }
  public static ProgressBar getRootAsProgressBar(ByteBuffer _bb, ProgressBar obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public ProgressBar __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public float progress() { int o = __offset(4); return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f; }

  public static int createProgressBar(FlatBufferBuilder builder,
      float progress) {
    builder.startObject(1);
    ProgressBar.addProgress(builder, progress);
    return ProgressBar.endProgressBar(builder);
  }

  public static void startProgressBar(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addProgress(FlatBufferBuilder builder, float progress) { builder.addFloat(0, progress, 0.0f); }
  public static int endProgressBar(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

