// automatically generated by the FlatBuffers compiler, do not modify

package AllWatchSerialize;

public final class Requirements {
  private Requirements() { }
  public static final short color = 0;
  public static final short images = 1;
  public static final short templates = 2;
  public static final short unicode = 3;
  public static final short icons = 4;
  public static final short png = 5;
  public static final short touchscreen = 6;

  public static final String[] names = { "color", "images", "templates", "unicode", "icons", "png", "touchscreen", };

  public static String name(int e) { return names[e]; }
}

