// automatically generated by the FlatBuffers compiler, do not modify

package AllWatchSerialize;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class ShapeAttributes extends Table {
  public static ShapeAttributes getRootAsShapeAttributes(ByteBuffer _bb) { return getRootAsShapeAttributes(_bb, new ShapeAttributes()); }
  public static ShapeAttributes getRootAsShapeAttributes(ByteBuffer _bb, ShapeAttributes obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public ShapeAttributes __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public short type() { int o = __offset(4); return o != 0 ? bb.getShort(o + bb_pos) : 0; }
  public boolean fill() { int o = __offset(6); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }

  public static int createShapeAttributes(FlatBufferBuilder builder,
      short type,
      boolean fill) {
    builder.startObject(2);
    ShapeAttributes.addType(builder, type);
    ShapeAttributes.addFill(builder, fill);
    return ShapeAttributes.endShapeAttributes(builder);
  }

  public static void startShapeAttributes(FlatBufferBuilder builder) { builder.startObject(2); }
  public static void addType(FlatBufferBuilder builder, short type) { builder.addShort(0, type, 0); }
  public static void addFill(FlatBufferBuilder builder, boolean fill) { builder.addBoolean(1, fill, false); }
  public static int endShapeAttributes(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

