// automatically generated by the FlatBuffers compiler, do not modify

package AllWatchSerialize;

public final class Shape {
  private Shape() { }
  public static final short Ellipse = 0;
  public static final short Rectangle = 1;

  public static final String[] names = { "Ellipse", "Rectangle", };

  public static String name(int e) { return names[e]; }
}

