// automatically generated by the FlatBuffers compiler, do not modify

package AllWatchSerialize;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class Style extends Table {
  public static Style getRootAsStyle(ByteBuffer _bb) { return getRootAsStyle(_bb, new Style()); }
  public static Style getRootAsStyle(ByteBuffer _bb, Style obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public Style __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public short absoluteWidth() { int o = __offset(4); return o != 0 ? bb.getShort(o + bb_pos) : 0; }
  public short absoluteHeight() { int o = __offset(6); return o != 0 ? bb.getShort(o + bb_pos) : 0; }
  public long backgroundColor() { int o = __offset(8); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public long borderColor() { int o = __offset(10); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public Background background() { return background(new Background()); }
  public Background background(Background obj) { int o = __offset(12); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }
  public short x() { int o = __offset(14); return o != 0 ? bb.getShort(o + bb_pos) : 0; }
  public short y() { int o = __offset(16); return o != 0 ? bb.getShort(o + bb_pos) : 0; }
  public short marginTop() { int o = __offset(18); return o != 0 ? bb.getShort(o + bb_pos) : 0; }
  public short marginBottom() { int o = __offset(20); return o != 0 ? bb.getShort(o + bb_pos) : 0; }
  public short marginLeft() { int o = __offset(22); return o != 0 ? bb.getShort(o + bb_pos) : 0; }
  public short marginRight() { int o = __offset(24); return o != 0 ? bb.getShort(o + bb_pos) : 0; }
  public double width() { int o = __offset(26); return o != 0 ? bb.getDouble(o + bb_pos) : 0.0; }
  public double height() { int o = __offset(28); return o != 0 ? bb.getDouble(o + bb_pos) : 0.0; }
  public double offsetX() { int o = __offset(30); return o != 0 ? bb.getDouble(o + bb_pos) : 0.0; }
  public double offsetY() { int o = __offset(32); return o != 0 ? bb.getDouble(o + bb_pos) : 0.0; }

  public static int createStyle(FlatBufferBuilder builder,
      short absoluteWidth,
      short absoluteHeight,
      long backgroundColor,
      long borderColor,
      int backgroundOffset,
      short x,
      short y,
      short marginTop,
      short marginBottom,
      short marginLeft,
      short marginRight,
      double width,
      double height,
      double offsetX,
      double offsetY) {
    builder.startObject(15);
    Style.addOffsetY(builder, offsetY);
    Style.addOffsetX(builder, offsetX);
    Style.addHeight(builder, height);
    Style.addWidth(builder, width);
    Style.addBorderColor(builder, borderColor);
    Style.addBackgroundColor(builder, backgroundColor);
    Style.addBackground(builder, backgroundOffset);
    Style.addMarginRight(builder, marginRight);
    Style.addMarginLeft(builder, marginLeft);
    Style.addMarginBottom(builder, marginBottom);
    Style.addMarginTop(builder, marginTop);
    Style.addY(builder, y);
    Style.addX(builder, x);
    Style.addAbsoluteHeight(builder, absoluteHeight);
    Style.addAbsoluteWidth(builder, absoluteWidth);
    return Style.endStyle(builder);
  }

  public static void startStyle(FlatBufferBuilder builder) { builder.startObject(15); }
  public static void addAbsoluteWidth(FlatBufferBuilder builder, short absoluteWidth) { builder.addShort(0, absoluteWidth, 0); }
  public static void addAbsoluteHeight(FlatBufferBuilder builder, short absoluteHeight) { builder.addShort(1, absoluteHeight, 0); }
  public static void addBackgroundColor(FlatBufferBuilder builder, long backgroundColor) { builder.addLong(2, backgroundColor, 0L); }
  public static void addBorderColor(FlatBufferBuilder builder, long borderColor) { builder.addLong(3, borderColor, 0L); }
  public static void addBackground(FlatBufferBuilder builder, int backgroundOffset) { builder.addOffset(4, backgroundOffset, 0); }
  public static void addX(FlatBufferBuilder builder, short x) { builder.addShort(5, x, 0); }
  public static void addY(FlatBufferBuilder builder, short y) { builder.addShort(6, y, 0); }
  public static void addMarginTop(FlatBufferBuilder builder, short marginTop) { builder.addShort(7, marginTop, 0); }
  public static void addMarginBottom(FlatBufferBuilder builder, short marginBottom) { builder.addShort(8, marginBottom, 0); }
  public static void addMarginLeft(FlatBufferBuilder builder, short marginLeft) { builder.addShort(9, marginLeft, 0); }
  public static void addMarginRight(FlatBufferBuilder builder, short marginRight) { builder.addShort(10, marginRight, 0); }
  public static void addWidth(FlatBufferBuilder builder, double width) { builder.addDouble(11, width, 0.0); }
  public static void addHeight(FlatBufferBuilder builder, double height) { builder.addDouble(12, height, 0.0); }
  public static void addOffsetX(FlatBufferBuilder builder, double offsetX) { builder.addDouble(13, offsetX, 0.0); }
  public static void addOffsetY(FlatBufferBuilder builder, double offsetY) { builder.addDouble(14, offsetY, 0.0); }
  public static int endStyle(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

