// automatically generated by the FlatBuffers compiler, do not modify

package AllWatchSerialize;

public final class Type {
  private Type() { }
  public static final short HorizontalLayout = 0;
  public static final short VerticalLayout = 1;
  public static final short Text = 2;
  public static final short Label = 3;
  public static final short Item = 4;
  public static final short Container = 5;
  public static final short Shape = 6;
  public static final short Card = 7;

  public static final String[] names = { "HorizontalLayout", "VerticalLayout", "Text", "Label", "Item", "Container", "Shape", "Card", };

  public static String name(int e) { return names[e]; }
}

