# automatically generated by the FlatBuffers compiler, do not modify

# namespace: AllWatchSerialize

class Attributes(object):
    NONE = 0
    LayoutAttributes = 1
    TextAttributes = 2
    ShapeAttributes = 3
    CardAttributes = 4

