# automatically generated by the FlatBuffers compiler, do not modify

# namespace: AllWatchSerialize

class CommandType(object):
    NONE = 0
    Handshake = 1
    Application = 2
    View = 3
    Action = 4
    Open = 5
    Back = 6
    Update = 7

