# automatically generated by the FlatBuffers compiler, do not modify

# namespace: AllWatchSerialize

import flatbuffers

class Component(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsComponent(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Component()
        x.Init(buf, n + offset)
        return x

    # Component
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Component
    def CmpType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # Component
    def Cmp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            from flatbuffers.table import Table
            obj = Table(bytearray(), 0)
            self._tab.Union(obj, o)
            return obj
        return None

def ComponentStart(builder): builder.StartObject(2)
def ComponentAddCmpType(builder, cmpType): builder.PrependUint8Slot(0, cmpType, 0)
def ComponentAddCmp(builder, cmp): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(cmp), 0)
def ComponentEnd(builder): return builder.EndObject()
