# automatically generated by the FlatBuffers compiler, do not modify

# namespace: AllWatchSerialize

class DefaultStyle(object):
    Notification = 0
    TextWall = 1
    ToBottom = 2
    ToTop = 3
    Center = 4

