# automatically generated by the FlatBuffers compiler, do not modify

# namespace: AllWatchSerialize

class DefaultDatatypes(object):
    Text = 0
    Media = 1
    List = 2
    Map = 3
    Messaging = 4
    Custom = 5

