# automatically generated by the FlatBuffers compiler, do not modify

# namespace: AllWatchSerialize

import flatbuffers

class LayoutAttributes(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsLayoutAttributes(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = LayoutAttributes()
        x.Init(buf, n + offset)
        return x

    # LayoutAttributes
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # LayoutAttributes
    def Spacing(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int16Flags, o + self._tab.Pos)
        return 0

def LayoutAttributesStart(builder): builder.StartObject(1)
def LayoutAttributesAddSpacing(builder, spacing): builder.PrependInt16Slot(0, spacing, 0)
def LayoutAttributesEnd(builder): return builder.EndObject()
