# automatically generated by the FlatBuffers compiler, do not modify

# namespace: AllWatchSerialize

import flatbuffers

class ProgressBar(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsProgressBar(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ProgressBar()
        x.Init(buf, n + offset)
        return x

    # ProgressBar
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ProgressBar
    def Progress(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

def ProgressBarStart(builder): builder.StartObject(1)
def ProgressBarAddProgress(builder, progress): builder.PrependFloat32Slot(0, progress, 0.0)
def ProgressBarEnd(builder): return builder.EndObject()
