# automatically generated by the FlatBuffers compiler, do not modify

# namespace: AllWatchSerialize

class Requirements(object):
    color = 0
    images = 1
    templates = 2
    unicode = 3
    icons = 4
    png = 5
    touchscreen = 6

