# automatically generated by the FlatBuffers compiler, do not modify

# namespace: AllWatchSerialize

class Type(object):
    HorizontalLayout = 0
    VerticalLayout = 1
    Text = 2
    Label = 3
    Item = 4
    Container = 5
    Shape = 6
    Card = 7

